# Aplicando Python para análisis de precios: descarga, manejo y análisis de datos

<img style="float: right; margin: 0px 0px 15px 15px;" src="https://upload.wikimedia.org/wikipedia/commons/0/0a/Python.svg" width="300px" height="100px" />

> En esta y en las siguientes dos clases veremos un caso de aplicación de simulación montecarlo en la toma de decisiones. Para lograr este objetivo, primero veremos (en esta clase) como manipular datos con *pandas*, tanto desde un archivo local de excel como remotamente desde Yahoo Finance.

> Python Data Analysis Library: pandas es una librería de código abierto, fácil de usar y que provee alto rendimiento en structuras de datos y herramientas de análisis de datos para el lenguaje de programación Python.

**Referencias:**
- http://pandas.pydata.org/
- http://www.learndatasci.com/python-finance-part-yahoo-finance-api-pandas-matplotlib/
- https://www.datacamp.com/community/tutorials/python-excel-tutorial

## 0. Motivación

<img style="float: right; margin: 0px 0px 15px 15px;" src="https://upload.wikimedia.org/wikipedia/commons/d/d7/Philippine-stock-market-board.jpg" width="400px" height="125px" />

Hace menos de una década, los instrumentos financieros estaban en la cúspide de la popularidad. Las instituciones financieras de todo el mundo estaban negociando miles de millones de dólares de estos instrumentos a diario, y los analistas cuantitativos estaban modelándolos utilizando el cálculo estocástico y el poderoso `C++`.

Sin embargo, el avance en los últimos años ha sido impresionante y las cosas han cambiado. Por una parte, la [crisis financiera del 2008](https://es.wikipedia.org/wiki/Crisis_financiera_de_2008) fue producida por los instrumentos financieros llamados *derivados*. Por otra parte, los volúmenes transaccionales han bajado y la demanda de modelado con `C++` se ha marchitado con ellos. Además, un nuevo jugador entró en la competencia... `¡Python!`

`Python` ha estado ganando muchos seguidores en la industria financiera en los últimos años y con razón. No en vano, junto a `R` son los lenguajes de programación más utilizados en cuanto a análisis financiero.

## 1. Descarga de datos de Yahoo! Finance
Para esto utilizaremos el paquete *pandas_datareader*.

**Nota**: Usualmente, las distribuciones de Python no cuentan, por defecto, con el paquete *pandas_datareader*. Por lo que será necesario instalarlo aparte:
- buscar en inicio "Anaconda prompt" y ejecutarlo como administrador;
- el siguiente comando instala el paquete en Anaconda: *conda install pandas-datareader*;
- una vez finalice la instalación correr el comando: *conda list*, y buscar que sí se haya instalado pandas-datareader

In [1]:
# Importar el modulo data del paquete pandas_datareader. La comunidad lo importa con el nombre de web
import pandas as pd
import pandas_datareader.data as web

In [2]:
# Librerías estándar para arreglos y gráficos
import matplotlib.pyplot as plt
%matplotlib inline

import numpy as np

Primero importaremos datos desde un archivo con extensión `.csv`

In [4]:
#Importar datos de un archivo csv
archivo='FB.csv'
data=pd.read_csv(archivo)
data

,Date,Open,High,Low,Close,Adj Close,Volume
0,2015-01-02,78.580002,78.930000,77.699997,78.449997,78.449997,18177500
1,2015-01-05,77.980003,79.250000,76.860001,77.190002,77.190002,26452200
2,2015-01-06,77.230003,77.589996,75.360001,76.150002,76.150002,27399300
3,2015-01-07,76.760002,77.360001,75.820000,76.150002,76.150002,22045300
4,2015-01-08,76.739998,78.230003,76.080002,78.180000,78.180000,23961000
5,2015-01-09,78.199997,78.620003,77.199997,77.739998,77.739998,21157000
6,2015-01-12,77.839996,78.000000,76.209999,76.720001,76.720001,19190200
7,2015-01-13,77.230003,78.080002,75.849998,76.449997,76.449997,25179600
8,2015-01-14,76.419998,77.199997,76.029999,76.279999,76.279999,25741000
9,2015-01-15,76.400002,76.570000,73.540001,74.050003,74.050003,34134000
10,2015-01-16,74.040001,75.320000,73.839996,75.180000,75.180000,21791500
11,2015-01-20,75.720001,76.309998,74.820000,76.239998,76.239998,22821600
12,2015-01-21,76.160004,77.300003,75.849998,76.739998,76.739998,25096700
13,2015-01-22,77.169998,77.750000,76.680000,77.650002,77.650002,19519500
14,2015-01-23,77.650002,78.190002,77.040001,77.830002,77.830002,16746500
15,2015-01-26,77.980003,78.470001,77.290001,77.500000,77.500000,19260800
16,2015-01-27,76.709999,76.879997,75.629997,75.779999,75.779999,20110000
17,2015-01-28,76.900002,77.639999,76.000000,76.239998,76.239998,53306400
18,2015-01-29,76.849998,78.019997,74.209999,78.000000,78.000000,61293500
19,2015-01-30,78.000000,78.160004,75.750000,75.910004,75.910004,42649500
20,2015-02-02,76.110001,76.139999,73.750000,74.989998,74.989998,41955300
21,2015-02-03,75.190002,75.580002,73.860001,75.400002,75.400002,26957700
22,2015-02-04,75.089996,76.349998,75.010002,75.629997,75.629997,20277400
23,2015-02-05,75.709999,75.980003,75.209999,75.610001,75.610001,15062600
24,2015-02-06,75.680000,75.699997,74.250000,74.470001,74.470001,21211000
25,2015-02-09,74.050003,74.830002,73.449997,74.440002,74.440002,16194300
26,2015-02-10,74.849998,75.339996,74.500000,75.190002,75.190002,15811300
27,2015-02-11,75.089996,76.750000,75.029999,76.510002,76.510002,20877400
28,2015-02-12,76.860001,76.870003,75.889999,76.230003,76.230003,17235000
29,2015-02-13,76.459999,76.480003,75.500000,75.739998,75.739998,18621900
...,...,...,...,...,...,...,...
976,2018-11-15,142.330002,144.839996,140.830002,143.850006,143.850006,30320300
977,2018-11-16,141.070007,141.770004,137.770004,139.529999,139.529999,37250600
978,2018-11-19,137.610001,137.750000,131.210007,131.550003,131.550003,44362700
979,2018-11-20,127.029999,134.160004,126.849998,132.429993,132.429993,41939500
980,2018-11-21,134.399994,137.190002,134.130005,134.820007,134.820007,25469700
981,2018-11-23,133.649994,134.500000,131.259995,131.729996,131.729996,11886100
982,2018-11-26,133.000000,137.000000,132.779999,136.380005,136.380005,24263600
983,2018-11-27,135.750000,136.610001,133.710007,135.000000,135.000000,20750300
984,2018-11-28,136.279999,136.789993,131.850006,136.759995,136.759995,29847500
985,2018-11-29,135.919998,139.990005,135.660004,138.679993,138.679993,24238700
986,2018-11-30,138.259995,140.970001,137.360001,140.610001,140.610001,25732600
987,2018-12-03,143.000000,143.679993,140.759995,141.089996,141.089996,24819200
988,2018-12-04,140.729996,143.389999,137.160004,137.929993,137.929993,30307400
989,2018-12-06,133.820007,139.699997,133.669998,139.630005,139.630005,28218100
990,2018-12-07,139.250000,140.869995,136.660004,137.419998,137.419998,21195500
991,2018-12-10,139.600006,143.050003,139.009995,141.850006,141.850006,26422200
992,2018-12-11,143.880005,143.880005,141.100006,142.080002,142.080002,20300300
993,2018-12-12,143.080002,147.190002,142.509995,144.500000,144.500000,23696900
994,2018-12-13,145.570007,145.850006,143.190002,145.009995,145.009995,18148600
995,2018-12-14,143.339996,146.009995,142.509995,144.059998,144.059998,21785800
996,2018-12-17,143.080002,144.919998,138.419998,140.190002,140.190002,24334000
997,2018-12-18,141.080002,145.929993,139.830002,143.660004,143.660004,24709100
998,2018-12-19,141.210007,144.910004,132.500000,133.240005,133.240005,57404900
999,2018-12-20,130.699997,135.570007,130.000000,133.399994,133.399994,40297900
1000,2018-12-21,133.389999,134.899994,123.419998,124.949997,124.949997,56901500
1001,2018-12-24,123.099998,129.740005,123.019997,124.059998,124.059998,22066000
1002,2018-12-26,126.000000,134.240005,125.889999,134.179993,134.179993,39723400
1003,2018-12-27,132.440002,134.990005,129.669998,134.520004,134.520004,31202500
1004,2018-12-28,135.339996,135.919998,132.199997,133.199997,133.199997,22627600
1005,2018-12-31,134.449997,134.639999,129.949997,131.089996,131.089996,24625300

Ahora lo haremos desde Yahoo Finance

In [ ]:
# Escribir una función para generalizar la exportación desde Yahoo

In [ ]:
# Instrumentos a descargar

#### La api de yahoo es inestable. Puede ser que nos toque intentar varias veces antes de tener éxito

In [ ]:
# Obtenemos los precios ajustados en el cierre

¿Cómo lucen estos datos?

In [ ]:
# Graficar

Una vez tenemos los datos, podemos operar con ellos. Por ejemplo un resumen de datos estadísticos se podría obtener con

In [ ]:
# Método describe

## 2. Rendimientos diarios

Para una sucesión de precios $\{S_t\}_{t=0}^{n}$, el rendimiento simple $R_t$ se define como el el cambio porcentual
$$
R_t=\frac{S_t-S_{t-1}}{S_{t-1}}
$$
para $t=1,\ldots,n$.

Para el ejemplo en curso, ¿cómo calcular esto?

In [ ]:
# Método shift

In [ ]:
# Entonces los rendimientos se calculan como

In [ ]:
# Método pct_change

y la gráfica de los rendimientos se puede obtener como...

In [ ]:
# Gráfica

Donde se observa que el rendimiento tiene una tendencia constante y, por tanto, se puede plantear la hipótesis de que se puede modelar usando un proceso estocástico estacionario en media.

Otro rendimiento usado con frecuencia es el rendimiento continuamente compuesto o rendimiento logaritmico. Éste, está definido como

$$
r_t=\ln\left(\frac{S_t}{S_{t-1}}\right).
$$

**Esta ecuación sólo es válida cuando se tienen periodos cortos de tiempo**
Es fácil darse cuenta que $r_t=\ln(1+R_t)$.

**Nota:** ver gráficamente que si $0\leq|x|\ll 1$, entonces $\ln(1+x)\approx x$.

Para este caso, la fórmula del rendimiento continuamente compuesto se translada facilmente a código Python (obtener, graficar y comparar).

In [ ]:
# Rendimiento logarítmico

In [ ]:
# Gráfica

In [ ]:
# Valor absoluto de la diferencia

Donde se observa que el rendimiento tiene una tendencia constante y, por tanto, se puede plantear la hipótesis de que se puede modelar usando un proceso estocástico estacionario en media.

Podemos incluso plantear la hipótesis de que los log rendimientos son normales...

In [ ]:
# Media y volatilidad de rendimientos

___
Recapitulando, hoy aprendimos a obtener datos con pandas-datareader directamente desde un archivo local ó fuentes remotas.

Por otra parte, estudiamos los rendimientos diarios y dimos con la conclusión de que se podrían modelar como un proceso estocástico estacionario normal.

La siguiente clase veremos como simular escenarios de comportamiento de los precios futuros (no determinístico, no sabemos como se comporta, muchas posibilidades: montecarlo) a partir de datos de ingresos diarios.

Luego, con esas predicciones veremos la probabilidad de que el precio de las acciones quede por encima (debajo) de cierto umbral y con ello tomar decisiones de vender (comprar) estas acciones.